# .streamlit/secrets.toml

[snowflake]
user = "ramananth.p@cbre.com"
account = "idb33659.us-east-1"
warehouse = "dev_dedm_data_engineer_whs"
database = "dev_dedm_db"
schema = "LANDING_ZONE"
authenticator="externalbrowser"